- id: check-feature-tags
  name: Check feature tags
  description: Makes sure that no @current or @focus tags are present in the Gherkin feature files
  entry: check-feature-tags
  language: python
  files: .feature$
- id: check-dos2unix
  name: Check dos2unix
  description: Check that dos2unix is applied
  entry: check-dos2unix
  language: python
  files: .sh$